### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Klyper** [softmonkeyjapan/opencart-excel-export#12]
Wonderfull plugin for opencart and it works very good.
Would it be possible to add extra colums to the export file like company name and vat number and invoice number?

Thank you to put the plugin free online!

**Comment by softmonkeyjapan** [comment]
Just added the invoice number and VAT on export as list. Update the plugin, try it and let me know if everything is alright.

**Comment by Klyper** [comment]
Hi,

Thanks for the quick update. Did you also include the company name?
I installed it and i got an error. I copied it in a txt-file that you find below.
https://dl.dropboxusercontent.com/u/858887/error_opencart-excel-export.txt

Thank you for updating the plugin so quickly.

**Comment by softmonkeyjapan** [comment]
The company name was already include under the `store name` column. About the error, I'm gonna try to make a quick fix, but this is weird.

**Comment by Klyper** [comment]
Thank you very much.
But i mean the company name of the buyer not of the seller.

If their is anything i can do to help just ask.
You have already been a very great help!

**Comment by softmonkeyjapan** [comment]
Could you tell me the data you have within your `oc_tax_rate` database table and which Opencart version are you using?

**Comment by Klyper** [comment]
![clipboard05](https://cloud.githubusercontent.com/assets/8761833/4263680/00fec1ca-3bf8-11e4-8402-2338ef85c301.jpg)
We are a small company and does not have to pay taxes for now. That's why their is an entry 'Vrijgesteld'.

**Comment by softmonkeyjapan** [comment]
Please try to replace the controller by this one : https://github.com/softmonkeyjapan/opencart-excel-export/blob/fix-vat/admin/controller/report/export_xls.php
and let me know

![screen shot 2014-09-14 at 9 28 41 pm](https://cloud.githubusercontent.com/assets/2499912/4263706/f8835b8a-3bf9-11e4-9a79-746cfbdf8c9d.png)

**Comment by Klyper** [comment]
It works! :)
Thank you!

Would it be a lot of work to add the company name of the company that sells in my store?
So that next to the name of the customer also the name of his company is present.

Thanks in advance

**Comment by softmonkeyjapan** [comment]
I just added the customer's company name. Hope it is working as you expected :)
