### ISSUE TITLE
Date format in selection

### ISSUE THREAD

**Issue by dmsims** [softmonkeyjapan/opencart-excel-export#15]
The Date start and Date end on the export form are shown in US format

The site is setup in admin to use UK format dates

![oc excel dates](https://cloud.githubusercontent.com/assets/4712953/6878002/0532f44e-d4cf-11e4-939e-182962963f46.png)

**Comment by softmonkeyjapan** [comment]
Oh wow, I never thought about that. Lemme check it out and make a fix this weekend.

**Comment by dmsims** [comment]
OK the date displays correctly initially - thank you
But if you use the sate picker it reverts to USA format (and show results from 2013)
If you type dates 01/01/2015 to 01/03/2015 it show results from the year 2013

**Comment by softmonkeyjapan** [comment]
I cannot reproduce this issue on my end. About the date picker and your initial problem, I think this was an OC default behavior (e,g, admin/index.php?route=report/sale_order). According to their internal code, they use `yy-mm-dd` (https://github.com/opencart/opencart/blob/v1.5.6.x/upload/admin/view/template/sale/order_list.tpl#L159) so even though you setup UK format dates in your admin, I don't think this is possible that the datepickers are displaying the right format
