### ISSUE TITLE
Generated XLSX invoice is broken according Excel 2010

### ISSUE THREAD

**Issue by SelfMan** [softmonkeyjapan/opencart-excel-export#5]
The invoice got generated without problems, but EXEL is complaining that "Excel fond unreadable content in "export-order-123.xlsx". Doyou want to recover the contents of this workbook? if you trust the source of this workbook, click Yes.
The following screen states: Excel wasable to open the file by repairing or removing the unreadable content. Removed Records" Merge cells from /xl/worksheets/sheet1.xml part
The XML itself is valid. The generated order list xlsx is ok and does not thow any errors. The problem is only in the invoice.

**Comment by SelfMan** [comment]
I've been digging a bit and found out that the generated sheet1.xml contains merged cells for product code, but are possiotioned one row up.( row 22 instead of row 23)

**Comment by SelfMan** [comment]
Ok, fix is: admin\controller\report\export_xls.php line 409
$this->objPHPExcel->getActiveSheet()->mergeCells('A21:C21');
remove or put a // comment in front.

Enhancement - lafter ine 47 put
$this->objPHPExcel->getActiveSheet()->mergeCells('D'.$counter.':E'.$counter); // merge product model cells

**Comment by softmonkeyjapan** [comment]
Sounds good to me. Could you make a pull request so I can review the code and merge it?
Thanks

**Comment by SelfMan** [comment]
Done... my first pull request on github. I hope its ok.

**Comment by softmonkeyjapan** [comment]
Yep, sounds good to me and works well. I'm closing this issue.  
Thanks
