### ISSUE TITLE
excel_library.zip not downloadable from http://www.soft-monkey.com/tmp/excel_library.zip

### ISSUE THREAD

**Issue by paynechia** [softmonkeyjapan/opencart-excel-export#7]
Hi,

I tried to download "excel_library.zip" from http://www.soft-monkey.com/tmp/excel_library.zip but the file is no longer there.

Can you please share us the excel_library.zip ?

Thank you~

**Comment by softmonkeyjapan** [comment]
Hi,

Thanks for your feedback. I just updated the documentation. Also note that you were able to find that library inside the `system` folder of this repo.  

Thanks
